/**
 * Skill taxonomy for the job-description matcher.
 *  - `aliases`  : how a JD may phrase it (used to FIND requirements and to canonicalise them)
 *  - `evidence` : literal terms looked for in Vishal's own content (profile + case studies).
 *                 Empty = nothing on the site supports it, so it can only ever be "gap".
 *  - `related`  : other skills whose evidence makes this a "partial" (adjacent, not the same).
 * Matching is literal, so the matcher can never claim something the site doesn't say.
 * Includes skills Vishal does NOT list (Docker, Kubernetes, …) so they are detected and shown as gaps.
 */
export type Skill = { id: string; name: string; aliases: string[]; evidence: string[]; related?: string[] };

const s = (
  id: string,
  name: string,
  aliases: string[],
  evidence: string[],
  related: string[] = [],
): Skill => ({
  id,
  name,
  aliases,
  evidence,
  related,
});

export const SKILLS: Skill[] = [
  // languages
  s("java", "Java", ["java", "jdk", "jvm", "j2ee", "jee"], ["java"]),
  s("javascript", "JavaScript", ["javascript", "js", "ecmascript", "es6"], ["javascript"]),
  s("typescript", "TypeScript", ["typescript"], ["typescript"], ["javascript"]),
  s("python", "Python", ["python"], ["python"]),
  s("kotlin", "Kotlin", ["kotlin"], ["kotlin"]),
  s("cpp", "C++", ["c++", "cpp"], []),
  s("csharp", "C#", ["c#", "csharp", ".net", "dotnet", "asp.net"], []),
  s("go", "Go", ["golang", "go lang"], []),
  s("rust", "Rust", ["rust"], []),
  s("php", "PHP", ["php", "laravel"], []),
  s("ruby", "Ruby", ["ruby", "ruby on rails", "rails"], []),
  s("swift", "iOS / Swift", ["ios", "swift", "swiftui", "objective-c"], [], ["flutter", "react-native"]),
  // web & backend
  s("spring-boot", "Spring Boot", ["spring boot", "springboot"], ["spring boot"], ["java"]),
  s("spring", "Spring", ["spring", "spring framework", "spring mvc", "spring cloud"], ["spring"]),
  s("spring-security", "Spring Security", ["spring security"], ["spring security"], ["security"]),
  s("jpa", "JPA / Spring Data", ["jpa", "spring data", "spring data jpa"], ["spring data jpa"]),
  s("hibernate", "Hibernate", ["hibernate", "orm"], [], ["jpa"]),
  s(
    "microservices",
    "Microservices",
    ["microservices", "microservice", "service-oriented", "soa"],
    ["microservices"],
  ),
  s(
    "rest",
    "REST APIs",
    [
      "restful",
      "rest api",
      "rest apis",
      "restful api",
      "restful apis",
      "web api",
      "web apis",
      "api development",
      "api design",
    ],
    ["rest api", "rest apis"],
  ),
  s("graphql", "GraphQL", ["graphql"], [], ["rest"]),
  s(
    "api-integration",
    "API integration",
    [
      "api integration",
      "api integrations",
      "third-party api",
      "third-party apis",
      "third party apis",
      "integrations",
      "function calling",
      "tool calling",
    ],
    ["api integration", "function calling", "brevo", "agora"],
  ),
  s("nodejs", "Node.js", ["node", "nodejs", "node.js"], ["node.js", "nodejs"], ["javascript"]),
  s("express", "Express", ["expressjs", "express.js"], [], ["nodejs"]),
  s("react", "React", ["react", "reactjs", "react.js", "react js"], ["react"]),
  s("nextjs", "Next.js", ["nextjs", "next.js"], ["next.js"], ["react"]),
  s("angular", "Angular", ["angular", "angularjs"], ["angular", "angularjs"]),
  s("vue", "Vue", ["vue", "vuejs", "vue.js", "nuxt"], [], ["react", "angular"]),
  s("redux", "Redux", ["redux", "state management"], [], ["react"]),
  s("html-css", "HTML & CSS", ["html", "html5", "css", "css3", "html & css", "html/css"], ["html5", "css3"]),
  s("tailwind", "Tailwind CSS", ["tailwind", "tailwindcss", "tailwind css"], ["tailwind css"], ["html-css"]),
  s("bootstrap", "Bootstrap", ["bootstrap", "sass", "scss"], [], ["html-css"]),
  s("threejs", "Three.js / WebGL", ["three.js", "threejs", "webgl", "3d graphics"], ["three.js"]),
  s(
    "frontend",
    "Frontend development",
    ["frontend", "front-end", "front end", "ui development", "web development"],
    ["frontend", "react", "next.js"],
  ),
  s("backend", "Backend development", ["backend", "back-end", "back end", "server-side"], ["backend"]),
  s(
    "fullstack",
    "Full-stack development",
    ["full stack", "full-stack", "fullstack"],
    ["full-stack", "full stack"],
  ),
  // mobile
  s("flutter", "Flutter", ["flutter"], ["flutter"]),
  s("dart", "Dart", ["dart"], ["dart"]),
  s("react-native", "React Native", ["react native"], ["react native"], ["react", "flutter"]),
  s("android", "Android", ["android"], ["android"]),
  s(
    "mobile",
    "Mobile development",
    ["mobile", "mobile app", "mobile apps", "mobile development", "mobile applications"],
    ["mobile"],
  ),
  // data
  s(
    "sql",
    "SQL",
    ["sql", "mysql", "relational database", "relational databases", "rdbms", "database design", "databases"],
    ["sql", "mysql"],
  ),
  s("postgresql", "PostgreSQL", ["postgresql", "postgres"], [], ["sql"]),
  s("oracle", "Oracle / PL-SQL", ["oracle", "pl/sql", "plsql"], [], ["sql"]),
  s("sqlserver", "SQL Server", ["sql server", "mssql", "t-sql"], [], ["sql"]),
  s("mongodb", "MongoDB", ["mongodb", "mongo"], ["mongodb"]),
  s("nosql", "NoSQL", ["nosql", "document database", "document databases"], ["mongodb", "firestore"]),
  s("redis", "Redis / caching", ["redis", "caching", "memcached"], []),
  s("firebase", "Firebase", ["firebase"], ["firebase"]),
  s("firestore", "Firestore", ["firestore", "cloud firestore"], ["firestore"], ["nosql"]),
  // cloud & devops
  s("aws", "AWS", ["aws", "amazon web services", "ec2", "s3", "lambda"], ["aws", "amazon web services"]),
  s("azure", "Azure", ["azure"], [], ["aws", "cloud"]),
  s(
    "gcp",
    "Google Cloud",
    ["gcp", "google cloud", "google cloud platform"],
    [],
    ["aws", "cloud", "firebase"],
  ),
  s("cloud", "Cloud", ["cloud", "cloud computing"], ["cloud"]),
  s("docker", "Docker", ["docker", "containers", "containerization"], []),
  s("kubernetes", "Kubernetes", ["kubernetes", "k8s"], [], []),
  s(
    "cicd",
    "CI/CD",
    [
      "ci/cd",
      "cicd",
      "continuous integration",
      "continuous delivery",
      "continuous deployment",
      "jenkins",
      "github actions",
      "gitlab ci",
    ],
    [],
    ["vercel"],
  ),
  s("linux", "Linux", ["linux", "unix", "bash", "shell scripting"], []),
  s("terraform", "Terraform / IaC", ["terraform", "infrastructure as code", "ansible"], []),
  s("git", "Git / GitHub", ["git", "github", "version control", "gitlab", "bitbucket"], ["git", "github"]),
  s("maven", "Maven", ["maven", "gradle", "build tools"], ["maven"]),
  s("postman", "Postman", ["postman", "api testing"], ["postman"]),
  s("vercel", "Vercel", ["vercel", "netlify"], ["vercel"]),
  // AI
  s("ai", "AI", ["ai", "artificial intelligence"], ["artificial intelligence", "generative ai"]),
  s(
    "genai",
    "Generative AI / LLMs",
    [
      "generative ai",
      "genai",
      "llm",
      "llms",
      "large language model",
      "large language models",
      "gemini",
      "chatgpt",
      "openai",
      "gpt",
    ],
    ["generative ai"],
    ["ai"],
  ),
  s(
    "rag",
    "RAG",
    [
      "rag",
      "retrieval augmented generation",
      "retrieval-augmented generation",
      "vector database",
      "vector databases",
      "embeddings",
    ],
    ["rag"],
    ["genai"],
  ),
  s("prompt", "Prompt engineering", ["prompt engineering", "prompting"], [], ["genai"]),
  s(
    "ml",
    "Machine learning",
    ["machine learning", "ml", "deep learning", "tensorflow", "pytorch", "data science", "nlp"],
    [],
    ["ai"],
  ),
  // practices & domains
  s(
    "security",
    "Security",
    [
      "security",
      "secure coding",
      "owasp",
      "authentication",
      "authorization",
      "oauth",
      "jwt",
      "encryption",
      "csrf",
    ],
    ["csrf", "aes-256", "spring security", "role-based access", "authentication"],
  ),
  s(
    "realtime",
    "Real-time systems",
    ["real-time", "realtime", "websocket", "websockets", "streaming"],
    ["real-time", "voip", "video calling"],
  ),
  s(
    "system-design",
    "System design",
    ["system design", "architecture", "scalable", "scalability", "distributed systems"],
    ["architecture", "scalable"],
  ),
  s(
    "oop",
    "Object-oriented programming",
    ["oop", "object oriented", "object-oriented", "design patterns"],
    [],
    ["java"],
  ),
  s("dsa", "Data structures & algorithms", ["data structures", "algorithms", "dsa", "problem solving"], []),
  s("testing", "Testing", ["testing", "unit testing", "junit", "jest", "test automation", "tdd", "qa"], []),
  s("agile", "Agile / Scrum", ["agile", "scrum", "kanban", "sprint"], []),
];

export const SKILL_BY_ID = new Map(SKILLS.map((k) => [k.id, k]));
