import { expect, test, type Page } from "@playwright/test";
import { gotoReady, loadIslands } from "./helpers";

/**
 * V3 · Phase 0: the three heavy sections below the fold (activity, stack map, contact form) are lazy islands.
 * Their code stays out of the first load, a grid-square placeholder holds their place, and the placeholder is
 * as tall as the real thing (styles/islands.css, generated by `pnpm islands --write`) so nothing jumps.
 */
const mockStatus = (page: Page) =>
  page.route("**/api/status", (r) =>
    r.fulfill({ json: { checkedAt: new Date().toISOString(), statuses: {} } }),
  );

const ISLANDS = ["activity", "stack", "contact-form"] as const;

test("at load every island is a placeholder, and none of their code has been requested", async ({ page }) => {
  await mockStatus(page);
  const scripts: string[] = [];
  page.on("response", async (r) => {
    if (r.url().includes("/_next/static/") && r.url().endsWith(".js")) scripts.push(r.url());
  });
  await gotoReady(page, "/");
  await page.waitForLoadState("networkidle");
  for (const name of ISLANDS) {
    const island = page.locator(`[data-island="${name}"]`);
    await expect(island.locator(".skel")).toHaveCount(1);
    await expect(island.getByRole("status")).toHaveAccessibleName(/^Loading /);
  }
  const before = scripts.length;
  await loadIslands(page);
  await page.waitForLoadState("networkidle");
  expect(scripts.length, "loading the islands fetches their chunks").toBeGreaterThan(before);
  for (const name of ISLANDS) await expect(page.locator(`[data-island="${name}"] .skel`)).toHaveCount(0);
});

for (const width of [360, 390, 640, 768, 1024, 1280, 1440]) {
  test(`@${width}px: each placeholder is within 60px of the loaded height`, async ({ page }) => {
    await mockStatus(page);
    await page.setViewportSize({ width, height: 900 });
    await gotoReady(page, "/");
    await page.waitForLoadState("networkidle");
    const height = (name: string) =>
      page.locator(`[data-island="${name}"]`).evaluate((el) => el.getBoundingClientRect().height);
    const before: Record<string, number> = {};
    for (const name of ISLANDS) before[name] = await height(name);
    await loadIslands(page);
    for (const name of ISLANDS) {
      const after = await height(name);
      expect(
        Math.abs(after - before[name]!),
        `${name}: placeholder ${before[name]} vs loaded ${after}`,
      ).toBeLessThanOrEqual(60);
    }
  });
}

test("jumping straight to the contact section still shows a working form", async ({ page }) => {
  await mockStatus(page);
  await gotoReady(page, "/#contact");
  await expect(page.getByRole("textbox", { name: /^Message/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /send/i })).toBeVisible();
});
