/**
 * pnpm islands [--url=http://localhost:3300] [--write]
 *
 * The three heavy sections below the fold (activity, stack map, contact form) load just before they
 * scroll into view. Until then a grid-square skeleton holds their place, and it must be as tall as the
 * real thing or the page jumps. This measures the loaded height at many widths on a running production
 * build (`pnpm build && pnpm start --port 3300`) and prints (or with --write, writes) styles/islands.css,
 * one min-height step per change. Heights only ever step at the largest value in the interval, so the
 * real content is never taller than its placeholder. Re-run after changing the content of those sections;
 * tests/e2e/islands.spec.ts fails when the placeholders drift by more than 60 px.
 */
import { chromium } from "@playwright/test";
import { writeFileSync } from "node:fs";

const url = process.argv.find((a) => a.startsWith("--url="))?.slice(6) ?? "http://localhost:3300";
const write = process.argv.includes("--write");

// Passed as a string on purpose: tsx adds a `__name` helper to named functions, which the page does not have.
const MEASURE = `(async () => {
  for (const id of ["github", "stack", "contact"]) {
    document.getElementById(id).scrollIntoView({ block: "start" });
    await new Promise((r) => setTimeout(r, 900));
  }
  await new Promise((r) => setTimeout(r, 1200));
  const tabs = document.querySelector('[aria-label="Contribution period"]');
  const cal = document.querySelector('[data-testid="contribution-calendar"]');
  const stack = document.querySelector('[data-island="stack"]');
  const form = document.querySelector('[data-island="contact-form"] form');
  if (!tabs || !cal || !stack || !form) return null;
  const card = cal.closest(".rounded-card");
  const stackBody = stack.firstElementChild;
  return {
    activity: Math.round(card.getBoundingClientRect().bottom - tabs.getBoundingClientRect().top),
    stack: Math.round(stackBody.getBoundingClientRect().height),
    form: Math.round(form.getBoundingClientRect().height),
  };
})()`;

type H = { activity: number; stack: number; form: number };
const BREAKPOINTS = new Set([640, 768, 1024]);
const widths: number[] = [];
for (let w = 340; w <= 1300; w += 20) widths.push(w);
widths.push(639, 640, 767, 768, 1023, 1024, 1279, 1280, 1440);
widths.sort((a, b) => a - b);
const W = [...new Set(widths)];

const browser = await chromium.launch();
const got = new Map<number, H>();
for (const w of W) {
  const page = await (await browser.newContext({ viewport: { width: w, height: 900 } })).newPage();
  await page.route("**/api/status", (r) =>
    r.fulfill({ json: { checkedAt: new Date().toISOString(), statuses: {} } }),
  );
  await page.goto(url, { waitUntil: "networkidle" });
  const h = (await page.evaluate(MEASURE)) as H | null;
  if (!h) throw new Error(`could not measure at ${w}px: is ${url} a production build with the islands?`);
  got.set(w, h);
  await page.context().close();
}
await browser.close();

const up = (n: number) => Math.ceil(n / 5) * 5;
const css: string[] = [
  "/*",
  " * Heights of the lazy islands' placeholders: the largest the real content gets in each width range, so the",
  " * swap never makes the page taller. GENERATED by `pnpm islands --write` from a production build; do not edit by hand.",
  " */",
];
for (const key of ["activity", "stack", "form"] as const) {
  const name = `.island-${key}`;
  let last = -1;
  const rules: string[] = [];
  W.forEach((w, i) => {
    const next = W[i + 1];
    const here = got.get(w)![key];
    const val = up(next === undefined || BREAKPOINTS.has(next) ? here : Math.max(here, got.get(next)![key]));
    if (val === last) return;
    last = val;
    rules.push(
      i === 0
        ? `${name} { min-height: ${val}px; }`
        : `@media (min-width: ${w}px) { ${name} { min-height: ${val}px; } }`,
    );
  });
  css.push(...rules);
}
const out = css.join("\n") + "\n";
if (write) {
  writeFileSync("styles/islands.css", out);
  console.log(`wrote styles/islands.css (${css.length - 4} rules)`);
} else console.log(out);
